### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by DeadSurfer** [ridicoulous/TelegramBotFramework#1]
Было бы круто если бы ты сделал пример использование

**Comment by ridicoulous** [comment]
@DeadSurfer done. see [here](https://github.com/ridicoulous/TelegramBotFramework/tree/master/TelegramBotFramework.Example).
Feel free to reopen this issue or open new, if you need more details.

**Comment by DeadSurfer** [comment]
Привет, слушай можешь мне отписать в телеграм пожалуйста @deadsurfer
